# Ubuntu 20.04 LTS (Focal Fossa)
ARG BASE_REGISTRY=docker.io/jawnsy
ARG BASE_IMAGE=coder-minimal-ubuntu
ARG BASE_TAG=focal

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

SHELL ["/bin/bash", "-c"]

USER coder
