name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # Re-build all images at 2am UTC every Monday (8pm CST/9pm CDT)
    #
    # This ensures we always start with a recent base image, which
    # reduces wasted space due to written-over files in the writable
    # layer, ensures packages are up-to-date (since many of these
    # images install the latest versions of packages available at
    # build time), and allow us to ensure that images continue to
    # be buildable from source (no removed packages).
    #
    # See: https://crontab.guru/#0_2_*_*_1
    - cron: "0 2 * * 1"

  workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  images-minimal-ubuntu-focal:
    name: images/minimal/ubuntu/focal
    runs-on: ubuntu-20.04
    permissions:
      actions: write # for cancel-workflow-action
      contents: read
      id-token: write
    steps:
      - name: Cancel previous runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/477254869654/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@coder-ci.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker gcr.io

      - name: Configure Docker for Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build coder-minimal-ubuntu:focal
        run: |
          ./scripts/build_image.sh \
            --name=coder-minimal-ubuntu \
            --path="${{ github.workspace }}/images/minimal/ubuntu/focal" \
            --tag=focal \
            --tag=latest \
            --pull-request="${{ github.event.number }}" \
            --push=true

  images-base-ubuntu-focal:
    name: images/base/ubuntu/focal
    runs-on: ubuntu-20.04
    needs:
      - images-minimal-ubuntu-focal
    permissions:
      actions: write # for cancel-workflow-action
      contents: read
      id-token: write
    steps:
      - name: Cancel previous runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/477254869654/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@coder-ci.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker gcr.io

      - name: Configure Docker for Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build coder-minimal-ubuntu:focal
        run: |
          ./scripts/build_image.sh \
            --name=coder-base-ubuntu \
            --path="${{ github.workspace }}/images/base/ubuntu/focal" \
            --tag=focal \
            --tag=latest \
            --pull-request="${{ github.event.number }}" \
            --push=true
