name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # Re-build all images at 2am UTC every Monday (8pm CST/9pm CDT)
    #
    # This ensures we always start with a recent base image, which
    # reduces wasted space due to written-over files in the writable
    # layer, ensures packages are up-to-date (since many of these
    # images install the latest versions of packages available at
    # build time), and allow us to ensure that images continue to
    # be buildable from source (no removed packages).
    #
    # See: https://crontab.guru/#0_2_*_*_1
    - cron: "0 2 * * 1"

  workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  image-minimal-ubuntu:
    runs-on: ubuntu-20.04
    name: image/minimal/ubuntu
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        uses: ./.github/actions/build-image
        with:
          path: ./images/minimal/ubuntu/focal
