# Container image scan workflow
name: security

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/security.yml

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/security.yml

  schedule:
    # Run scans at 4am UTC every day (12am CST/1am CDT)
    #
    # See: https://crontab.guru/#0_4_*_*_*
    - cron: "0 4 * * *"

  workflow_dispatch:

permissions:
  actions: write # for cancel-workflow-action
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

# Cancel in-progress runs for pull requests when developers push
# additional changes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  image-scan:
    name: "${{ matrix.image }}"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          # Ubuntu 20.04 LTS (Focal Fossa)
          - "coder-ubuntu-minimal:focal"
          - "coder-ubuntu-base:focal"
          # Ubuntu 22.04 LTS (Jammy Jellyfish)
          - "coder-ubuntu-minimal:jammy"
          - "coder-ubuntu-base:jammy"
          # Ubuntu rolling
          - "coder-ubuntu-minimal:rolling"
          - "coder-ubuntu-base:rolling"
          # Debian 11 (bullseye)
          - "coder-debian-minimal:bullseye"
          - "coder-debian-base:bullseye"
          # Debian testing
          - "coder-debian-minimal:testing"
          - "coder-debian-base:testing"
          # Debian unstable
          - "coder-debian-minimal:unstable"
          - "coder-debian-base:unstable"
      fail-fast: false
    steps:
      - name: Scan image with AquaSec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/jawnsy/${{ matrix.image }}"
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Scan image with Anchore Grype
        uses: anchore/scan-action@v3
        with:
          image: "docker.io/jawnsy/${{ matrix.image }}"
          severity-cutoff: "high"
          debug: true
